### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by 1094724913** [voletiv/mcvd-pytorch#22]
Hi!

When I was training on ucf101 with command:

 python main.py --config configs/ucf101.yml --data_path datasets/download_ucf_101/UCF101_h5 --exp ucf101 --ni

I received following error:
ucf101/logs/meters.pkl does not exist! Returning.
ERROR - main.py - 2023-08-05 11:15:09,283 - Traceback (most recent call last):
  File "main.py", line 404, in main
    runner.train()
  File "/home/jsun/PycharmProjects/mcvd-pytorch-master/runners/ncsn_runner.py", line 374, in train
    for batch, (X, y) in enumerate(dataloader):
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 174, in default_collate
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 174, in <listcomp>
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/opt/anaconda3/envs/vid/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 139, in default_collate
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable

Check the information and say that the data dimensions are not uniform, what should I do? 
Thank you

**Comment by xiekaige** [comment]
Hello,I woder do you solve the problem ?I have the same question as you.

![Image](https://github.com/user-attachments/assets/f491e547-46cb-422b-8dd0-071e6970093d)
